### ISSUE TITLE
FR: Being able to copy the text or at least make the text selectable

### ISSUE THREAD

**Issue by nicolasmarc1** [lstrzepek/obsidian-yt-transcript#1]
Hi! Nice plugin but it would be nice to be able to select  and copy the text too. Thanks!

**Comment by lstrzepek** [comment]
Hi! Thank you for using it :) Please try v0.4.0 now you can drag and drop the text

**Comment by nicolasmarc1** [comment]
thanks! i tried the update but you can't really select the text (or i am doing something wrong ?), when you click on the transcription and drop it onto the page  it copies a small arbitrary portion of the text. If making the ui of the transcript freely selectable is hard, why not just make a command that insert the transcript in the current page or a new page so that users can extract what they want from the transcript or search through it ...?

**Comment by lstrzepek** [comment]
v0.5.0 ready, try right click on the text and choose 'copy all' option

**Comment by nicolasmarc1** [comment]
perfect! thanks!  
btw idk if you want me to create another ticket but it would be nice to be able to trigger the command without having to have a perfect selection of the whole url, just put the cursor on the string of a youtube url and that it would recognize and extract that string using obsidian editor and a regex. 

Here's an example you could adapt from another plugin
https://github.com/zolrath/obsidian-auto-link-title/blob/18e6a809eb/editor-enhancements.ts

**Comment by lstrzepek** [comment]
Thanks for new ideas!
Because plugin is still in young age for me it is ok to have here all your ideas.
Please check v0.6.0 if your cursor is inside url and nothing else is selected then url should be properly fetched.

**Comment by nicolasmarc1** [comment]
Hi thanks! Did it work for you when you tried ? It's not working for me, idk why but getSelectedText seems to return a empty string. It's weird i tried with the obsidian-auto-link-title plugin and it works, not sure why it doesn't work in your case

**Comment by lstrzepek** [comment]
Hi can you paste a screenshot where you have a link in the editor and where you have a cursor when using the command?

**Comment by nicolasmarc1** [comment]
Sure here it is! I show you that i'm on the last version, that it doesn't work (twice) and that it work with obsidian-auto-link-title plugin.

https://user-images.githubusercontent.com/51007222/213266405-9d1e8cd4-0e4d-4334-baff-870adcffd2b7.mp4

But does it work for you? Because i'm looking at the debugger and getSelectedText return an empty url. Here's what i found: 


i think this might have to do with

        return {
          start: { line: cursor.line, ch: match.index ?? 0 },
          end: { line: cursor.line, ch: match.index ?? 0 + match[0].length },
        };

 why not just

          start: { line: cursor.line, ch: match.index },
          end: { line: cursor.line, ch: match.index + match[0].length }, 

like in obsidian-auto-link-title plugin. ?

In your case if match.index == 0 
![image](https://user-images.githubusercontent.com/51007222/213273529-81f6f4e0-3bc0-459e-b0fe-7d088607867b.png)


it returns 0 even for ch: match.index ?? 0 + match[0].length 
Which put the wordBoundaries.end at 0 and this is why you get an empty string

**Comment by lstrzepek** [comment]
Thank you very much @nicolasmarc1 for your detailed description. I hope version 0.6.4 will statisfy your needs

**Comment by lstrzepek** [comment]
I'll close this issue because initial bug was fix and this new problem will be tracked here #4

**Comment by gala8y** [comment]
Unfortunately copying text using 'Copy all' looses nice formatting.

this formatting is lost:
![image](https://user-images.githubusercontent.com/1263605/233443004-904cdabc-06c8-4c23-a04f-022f33faf805.png)

and copied text looks more like this:
![image](https://user-images.githubusercontent.com/1263605/233443467-3ed1512e-ab85-46c2-b2d7-5b9fade356bd.png)

Workaround is to use Developer Tools, copy whole element and convert output from html to markdown. Pasting retrieved transcript directly into the current note would be a nice option.

**Comment by rashmod** [comment]
I'd like to solve this one
