### ISSUE TITLE
Keep formatting in 'Copy all' option

### ISSUE THREAD

**Issue by lstrzepek** [lstrzepek/obsidian-yt-transcript#10]
Unfortunately copying text using 'Copy all' looses nice formatting.

this formatting is lost:
![image](https://user-images.githubusercontent.com/1263605/233443004-904cdabc-06c8-4c23-a04f-022f33faf805.png)

and copied text looks more like this:
![image](https://user-images.githubusercontent.com/1263605/233443467-3ed1512e-ab85-46c2-b2d7-5b9fade356bd.png)

Workaround is to use Developer Tools, copy whole element and convert output from html to markdown. Pasting retrieved transcript directly into the current note would be a nice option.

_Originally posted by @gala8y in https://github.com/lstrzepek/obsidian-yt-transcript/issues/1#issuecomment-1516701943_

**Comment by rashmod** [comment]
Seeing as this is still unresolved I'd like to solve this
