### ISSUE TITLE
Feature request: embed entire transcription into a note

### ISSUE THREAD

**Issue by Nick-Mazuk** [lstrzepek/obsidian-yt-transcript#17]
I often save YouTube videos into Obsidian if I've found them helpful or insightful. It would be great to get the entire transcription into a note.

This improves several workflows:

- Linking to any arbitrary point made in a video I've watched.
- Leverage AI to find trends among videos I've seen (e.g., the Smart Connections plugin).
- Using the Omnisearch plugin to find "something I saw in a video a while back but don't remember which one".
- etc.

**Comment by slkwrm** [comment]
+1 for this feature. I learn languages using Obsidian and want to be able to add my remarks and notes to the transcript. Thank you for a useful plug-in!

**Comment by YannickTemplay** [comment]
+1

**Comment by lstrzepek** [comment]
Hi, let me understand it better. So 'Copy all' option under right click is not enough for you because is too slow or it is missing some formatting?

**Comment by YannickTemplay** [comment]
No, this is just because I did not see the "copy all" :-(

Sorry

-1

**Comment by frugal-10191** [comment]
The only problems with Copy All are that it does not insert timestamps, and the line breaks are different to the transcript on the right hand leaf.
<img width="586" alt="image" src="https://github.com/lstrzepek/obsidian-yt-transcript/assets/82149736/95b0040c-d7a6-4300-a32e-a0c14a299f17">

**Comment by lstrzepek** [comment]
Please try v0.9.0 now copy all has same format as in pane
