### ISSUE TITLE
I can only drag the timestamp but not the transcription text

### ISSUE THREAD

**Issue by RiciTrisnaP** [lstrzepek/obsidian-yt-transcript#18]
When I use this plugin I encounter a problem where I can't drag any transcription text but I found that dragging the timestamp works normally, can you please help me?

**Comment by DeiseDaithi** [comment]
I am also experiencing the exact same issue. Can drag timestamps, but not transcribed text.

**Comment by RiciTrisnaP** [comment]
> I am also experiencing the exact same issue. Can drag timestamps, but not transcribed text.

I found that using custom snippets and then adding the style below would fix the problem:

.yt-transcript__transcript-block {
       user-select: text;
}

I believe the css of external theme to be the cause of this issue.

**Comment by DeiseDaithi** [comment]
Will try. Thanks.

**Comment by ichmoimeyo** [comment]
@RiciTrisnaP 

fantastic, thank you!

**Comment by jun6lee** [comment]
> > I am also experiencing the exact same issue. Can drag timestamps, but not transcribed text.
> 
> I found that using custom snippets and then adding the style below would fix the problem:
> 
> .yt-transcript__transcript-block { user-select: text; }
> 
> I believe the css of external theme to be the cause of this issue.


Seeing same behaviour and this workaround not working.

**Comment by jun6lee** [comment]
Can copy Timestamps, not text. Copy All on right-click works.

Am able to reproduce the issue as follows:
- Create a new vanilla vault
- Enable community plugins
- Add this plugin.
- Try using -- behaviour same. 
- Adding and enabling CSS Snippet
- Restart obsidian
- Try using -- behaviour same.

Might It be possible to give each block a right clock copy option and putting "Copy All" as an option up to near search?

**Comment by lstrzepek** [comment]
Please try v0.9.0 you should be able to left click on block and copy it

**Comment by lstrzepek** [comment]
S
