### ISSUE TITLE
transcipt retreiving english

### ISSUE THREAD

**Issue by ldmartin1024** [lstrzepek/obsidian-yt-transcript#2]
Appreciate your work. reporting transciption retreval is not in english in obsidian (latest version) when it is at youtube page.

**Comment by lstrzepek** [comment]
Hi! 
Can you explain a little bit more? I understand that you have a video which directly on YT has transcription in English but for some reason plugin is presenting it in other language? Can you paste here link to this vide?

**Comment by lstrzepek** [comment]
All I could do was to add lang and country params in settings. Hope that will work for you

**Comment by lstrzepek** [comment]
Any follow up on this one?
