### ISSUE TITLE
400 Error for Youtu.be url

### ISSUE THREAD

**Issue by se6wagner** [lstrzepek/obsidian-yt-transcript#24]
https://youtu.be/5stPFdegJpg?t=2028

https://www.youtube.com/watch?v=5stPFdegJpg

**Describe the bug**
When trying to fetch the transcript for the below URL, the plugin returns "Error loading transcript.", "Request failed, status 400"

**Youtube link**
(https://youtu.be/5stPFdegJpg)

**Expected behavior**
Plugin should automatically recognize short URL

Thanks for this awesome plugin mate!

**Comment by lstrzepek** [comment]
Hey thanks for feedback! Have you tried latest version where this bug should be fixed? 0.8.2?

**Comment by se6wagner** [comment]
yes, that fixed it. my bad sorry
