### ISSUE TITLE
Plugin ID mismatch

### ISSUE THREAD

**Issue by jsmm** [lstrzepek/obsidian-yt-transcript#3]
This plugin cannot be installed via Obsidian community plugin's pannel in Obsidian 1.1.9 in macOS 13.2. The error message is "Plugin ID mismatch".

I look forward to this plugin being really useful in my workflow. Thanks for sharing.

**Comment by ngirard** [comment]
I'm experiencing the same using Obsidian v1.1.12 on Ubuntu 22.04.

Cheers, and thanks for your work Łukasz !

**Comment by lstrzepek** [comment]
Hi! Thank you for info. Now it should be ok in version 0.6.3

**Comment by ngirard** [comment]
Great, thanks !
