### ISSUE TITLE
Option to parse url near cursor

### ISSUE THREAD

**Issue by jeffvogelsang** [lstrzepek/obsidian-yt-transcript#30]
**Is your feature request related to a problem? Please describe.**

The current YTranscript  behavior seems to be that you must highlight a URL in the text, and then select "YTranscript: Get YouTube transcript from selected url" in the command palette or by keyboard shortcut. If you have a valid YT URL highlighted in the text, then the plugin works fine.

If you don't 1) have a URL highlighted, 2) have extra characters highlighted around the URL, and/or 3) have only part of a URL highlighted, the plugin doesn't work. You'll get the new transcript pane, but it will just say "Loading..." forever.

**Describe the solution you'd like**

Similar to how to _Auto Link Title_ works, it would be great if YTranscript would find the url on the current line, proximate to the cursor, and automatically parse and use it. Then you could just make sure the cursor near on in the URL, and hit the hotkey. This would make the plugin much easier to use, and reduce the effort and errors around highlighting a URL in your notes.

**Comment by lstrzepek** [comment]
Hi @jeffvogelsang 
Thank you for your comment! :)
Actually it is working as you described as long as nothing else is selected, if you will place your cursor near to the url in same line then it will be working. 
I can think of unselecting first, so it maybe will be more user friendly but not sure if this is what you want

**Comment by SrGeneroso** [comment]
I would like to have the transcript when pressing a button, how would I pass a predefined text into it?
Right now I have this with the buttons plugin ```button
name Transcript
type command
action YTranscript: Get YouTube transcript from selected url
color purple
```
