### ISSUE TITLE
400 response

### ISSUE THREAD

**Issue by jason-o-matic** [lstrzepek/obsidian-yt-transcript#34]
**Plugin version**
0.9.1

**Describe the bug**
When I use the prompt and paste this url I get a 400 response.

**Youtube link**
https://youtu.be/YNOQzE1XTdU?si=knDhLoMoU0l4wOuB

**Expected behavior**
I expect to get a transcript.

**Comment by redactedscribe** [comment]
Related: #33

**Comment by lstrzepek** [comment]
Link from your description is working
