### ISSUE TITLE
FR: Allow behavior where dragging does not also grab the transcript

### ISSUE THREAD

**Issue by mariomui** [lstrzepek/obsidian-yt-transcript#36]
As a note taker, I sometimes only want specific content and specific time stamps so that I can keep the citations/annotations list concise.

Current behavior copies over the transcript chunk whenever I drag the timestamp over. I only need the timestamp.

**Comment by lstrzepek** [comment]
Hi! Thanks for reaching out! Have you tried to drag and drop directly timestamp?
