### ISSUE TITLE
Issue with video ID from youtube

### ISSUE THREAD

**Issue by johnsonblue75** [lstrzepek/obsidian-yt-transcript#4]
Hey I keep getting "impossible to retrieve Youtube ID. Looks like a nice plugin!

![image](https://user-images.githubusercontent.com/118084798/218318338-4de2fe12-2674-4aac-a5b5-8b5a587627d2.png)

Note that I installed with BRAT on Windows 11

**Comment by lstrzepek** [comment]
Hi @johnsonblue75 thank you for your info. I made quick fix in version 0.6.4.
How to avoid this problem:
- select full yt url
- place your cursor inside url

This version still not support partial selection nor placing cursor in link markdown. It has to one of above.

**Comment by johnsonblue75** [comment]
Holy cow you are the fastest, most responsive developer ever. Thanks!!!
