### ISSUE TITLE
YouTube API v1 is deprecated

### ISSUE THREAD

**Issue by tomodachi94** [lstrzepek/obsidian-yt-transcript#46]
YouTube API v1, the API this plugin is using, [has been deprecated](https://developers.google.com/youtube/v1_deprecation_notice) for a long time, and could be shut down at any time. The plugin developers should consider updating to use API v3.

**Comment by tomodachi94** [comment]
Here's the specific line of code:

https://github.com/lstrzepek/obsidian-yt-transcript/blob/master/src/fetch-transcript.ts#L50-L57

**Comment by canadaduane** [comment]
I believe the API has finally changed / stopped working. See also https://github.com/Kakulukian/youtube-transcript/issues/19

**Comment by lstrzepek** [comment]
Thank you very much for your help. All should be working right now. Please check v0.9.2 - update or reinstall.
