### ISSUE TITLE
Search through transcript

### ISSUE THREAD

**Issue by j-maffe** [lstrzepek/obsidian-yt-transcript#5]
Great plugin! I really think there's plenty of utility for a plugin like this. One feature that I would love to see implemented would be a search bar at the top. It could filter through the quote blocks and just show the matching ones.

**Comment by lstrzepek** [comment]
Thank you very much for warm words. This is great idea. As soon as I will be back to work I'll try to add it

**Comment by CristianoS1** [comment]
Great Plugin!
I second j-maffe feature request.

**Comment by trey-wallis** [comment]
@lstrzepek I could add this if you would like. In order to do this, I would recommend using some type of reactive framework. Svelte or React would work well.

**Comment by lstrzepek** [comment]
Thanks again @trey-wallis for contribution!
I'm curious about your feedback. 

@trey-wallis About title and modal I think we can create discussion (sorry for removing it from release). 
About title I think we should resign from external lib to fetch transcript and include this code into plugin. Thanks to that we can fetch more metadata (including title) from YouTube in one go. Maybe we can extend markup to include title when pasting link into obsidian...

**Comment by trey-wallis** [comment]
@lstrzepek You're welcome. I really enjoy the plugin. I think including the title as part of the external library code was a good idea. That way only 1 request is made.
