### ISSUE TITLE
Links from live not working

### ISSUE THREAD

**Issue by spiritualgeek** [lstrzepek/obsidian-yt-transcript#6]
I find that I, sometimes, need to utilise the URL as though the video is to be an embed, i.e. `https://www.youtube.com/embed/`?

This is a wonderful plugin. Please keep it going.

**Comment by lstrzepek** [comment]
Hi thank you for your comment. Can you elaborate a little why you are using embed in your notes and what is happening when you are trying to get transcript for this kind of link?

**Comment by spiritualgeek** [comment]
Seeing that this is Obsidian - Try the interview with Kepano as an e.g. - https://www.youtube.com/live/TkNTuFF2t-c?feature=share

It will not work unless you replace `live` with `embed`

**Comment by lstrzepek** [comment]
removing "feature=share" fixes problem
