### ISSUE TITLE
Problem with transcripts being only partially retrieved

### ISSUE THREAD

**Issue by gala8y** [lstrzepek/obsidian-yt-transcript#7]
Hi, thx for developing the plugin.

Unfortunately, I get transcripts missing text at the end.

**Comment by lstrzepek** [comment]
Hi! Thanks for your comment :)
Please provide link and info from which timestamp transcript is missing. Please also check if you can retrieve this missing part from transcript option directly on youtube

**Comment by jun6lee** [comment]
Eg: https://www.youtube.com/watch?v=4gFi285OhrQ --- a fairly long video.
If I want all the text, I change the lines in settings to say 50 or 60.

What it does is grab some batches, with an exception of the last one.
If I change then back to 5, I can see them coming through. Same again, except the last batch which would be less than 5.
If I change then to15, I can see those final lines. 

I think an option for those wanting to copy the entire transcript as raised in: 
https://github.com/lstrzepek/obsidian-yt-transcript/issues/8

... might be to set it to 1000, bit this brings back nothing as of now.
Hope this helps you get to the source of the issue. 

Love the plugin, just these fine-tuning bits I feel will make it an everyday tool for me!

**Comment by lstrzepek** [comment]
Sorry I can't reproduce this issue. For mentioned video I'm getting following transcript: "[Applause] the science delusion is the belief that science already understands the nature of reality ...... life affirming thank you [Applause] you"
I have it through "Copy all" option. Please check again

**Comment by jun6lee** [comment]
That's perfect. I actually just hadn't thought to right click!
It might be a worthy enhancement to put it up visibly as an icon up top.
https://lucide.dev/icon/clipboard-copy?search=copy

**Comment by lstrzepek** [comment]
Thanks for feedback! I'll check what is possible to make it more visible 🙂
