### ISSUE TITLE
Drag and drop *both* timestamp and transcript extract

### ISSUE THREAD

**Issue by CristianoS1** [lstrzepek/obsidian-yt-transcript#8]
I would love to be able in a single drag and drop to have pasted in my note either the timestamp link and the transcript extract.

Eventually could be one of the setting options: there you can choose if you want both of them to be pasted simultaneously or individually.

Thanks!

**Comment by trey-wallis** [comment]
This would be really helpful for creating block quotes from the transcript.

**Comment by lstrzepek** [comment]
Hi!
Please check new version 0.9.1. Hope you will enjoy :)
